export function solanaConfigPoolMainnet() {
    return [
      {
        token: {
          WBTC: 'SBTCB6pWqeDo6zGi9WVRMLCsKsN6JiR1RMUqvLtgSRv',
          renBTC: 'CDJWUqTcYTVAKXAVXoQZFes5JUFc7owSeq7eMQcDSbo5',
          WSOL: 'So11111111111111111111111111111111111111112',
          mSOL: 'mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So',
          USDC: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
          USDT: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
          USDH: 'USDH1SM1ojwWUga67PGrgFWUHibbjqMvuMaDkRJTgkX',
          JSOL:'7Q2afV64in6N6SeZsAAB81TJzwDoD6zpqmHkzi9Dcavn',
          stSOL:'7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj',
          UXD:'7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT',
          ETH:'7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs',
          soETH:'SL819j8K9FuFPL84UepVcFkEZqDUUvVzwDmJjCHySYj',
          xFTT:'Fr3W7NPVvdVbwMcHgA7Gx2wUxP43txdsn3iULJGFbKz9',
          FTT:'EzfgjvkSwthhgHaceR3LnKXUoRkP6NUhfghdaHAj1tUv',
          SRMet:'xnorPhAzWXUczCP3KjU5yDxmKKZi5cSbxytQ1LgE3kG',
          SRM:'SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt',
          RAY: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
          PRT:'PRT88RkA4Kg5z7pKnezeNH4mafTvtQdfFgpQTGRjz44',
          FRONT:'A9ik2NrpKRRG2snyTjofZQcTuav9yH3mNVHLsLiDQmYt',
          MNDE:'MNDEFzGvMt87ueuHvVU9VcTqsAP5b3fTGPsHuuPA5ey',
          RATIO:'ratioMVg27rSZbSvBopUvsdrGUzeALUfFma61mpxc8J',
          HBB:'HBB111SCo9jkCejsZfz8Ec8nH7T6THF8KEKSnvwT6XK6',
          SLND:'SLNDpmoWTVADgEdndyvWzroNL7zSi1dF9PC3xHGtPwp',
          PORT:'PoRTjZMPXb9T7dyU7tpLEZRQj7e6ssfAE62j2oQuc6y',
          SBR:'Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1',
          ORCA:'orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE',
          ALEPH :'3UCMiSnkcnkPE1pgQ5ggPCBv6dXgVUy16TmMUe1WpG9x',
          ATLAS:'ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx',
          FIDA:'EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp',
          HXRO:'HxhWkVpk5NS4Ltg5nij2G671CKXFRKPK8vy271Ub4uEK',
          MNGO:'MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac',
          SHDW:'SHDWyBxihqiCj6YekG2GUr7wqKLeLAMK1gHZck9pL6y',
          AVAX:'KgV1GvrHQmRBY8sHQQeUKwTm2r2h8t4C8qt12Cw1HVE',
          LINK:'2wpTofQ8SkACrkZWrZDjXPitYa8AwWgX8AfxdeBRRVLX',
          BNB:'9gP2kCy3wA1ctvYWQk75guqXuHfrEomqydHLtcTCqiLa',
          NOVA:'BDrL8huis6S5tpmozaAaT5zhE5A7ZBAB2jMMvpKEeF8A'
        },
        OrcaPoolList: {
          WSOLmSOL: {
            "address":"HQcY5n2zP6rW74fyFEhWeBd3LnJpBcZechkvJpmdb8cx",
            "tokenMintA":"So11111111111111111111111111111111111111112",
            decimalA:9,
            "tokenMintB":"mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So",
            decimalB:9,
            "tickSpacing":1
        },
          USDCUSDH: {
            stableSwap: "MARpDPs5A7XiyCWPNH8GsMWPLxmwNn9SBmKvPa9LzgA",
            rewarderKey: "rXhAofQCT7NN9TUqigyEAUzV1uLL4boeD8CRkNBSkYk",
            quarryKey: "H6TWopq51MkjYqtCy8xTRJrzm88esDWoNVpL87Akybwn",
            rewardToken: "Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1",
            rewardWrapper: "EVVDA3ZiAjTizemLGXNUN3gb6cffQFEYkFjFZokPmUPz",
            nameStableCoin: "USDCUSDH",
            referenceMainnet: 'USDH-USDC',
          },
          USDCUSDT: {
            "address":"4fuUiYxTQ6QCrdSq9ouBYcTM7bqSwYTSyLueGZLTy4T4",
            "whitelisted":true,
            "tokenMintA":"EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
            decimalA:6,
            "tokenMintB":"Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
            decimalB:6,
            "tickSpacing":1,
            nameStableCoin: 'USDCUSDT',
            referenceMainnet: 'USDT-USDC',
          },
          WBTCrenBTC: {
            stableSwap: 'BkwbeSfcX1h4thMDd7obGkHrPevf3QwgzJ4pCEqG18Lu',
            rewarderKey: 'rXhAofQCT7NN9TUqigyEAUzV1uLL4boeD8CRkNBSkYk',
            quarryKey: '4pp9vu4oVr61KmyW1byfXg613jhfsDAA6FCuLhw9ycMp',
            rewardToken: 'Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1',
            rewardWrapper: 'EVVDA3ZiAjTizemLGXNUN3gb6cffQFEYkFjFZokPmUPz',
            nameStableCoin: 'WBTCrenBTC',
            referenceMainnet: 'BTC-renBTC',
          },
          SRMetSRM: {
            stableSwap: 'SRMuKizofcAMicegrfSv7xs9q76tH1w8aAF7oX9FEWu',
            rewarderKey: 'rXhAofQCT7NN9TUqigyEAUzV1uLL4boeD8CRkNBSkYk',
            quarryKey: 'C7faBVAJad3obMyRxXn8dqbDJT7TT2A4oidKeELCMckp',
            rewardToken: 'Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1',
            rewardWrapper: 'EVVDA3ZiAjTizemLGXNUN3gb6cffQFEYkFjFZokPmUPz',
            nameStableCoin: 'SRMetSRM',
            referenceMainnet: 'SRMet-SRM',
          },
          FTTxFTT: {
            stableSwap: 'Bodz3SK3pzzskFdjwG5TXoavTzNLJbMV8VDQHvxkhTa1',
            rewarderKey: 'rXhAofQCT7NN9TUqigyEAUzV1uLL4boeD8CRkNBSkYk',
            quarryKey: 'FdHVdkarMfbpPhiAhHtKK6PgH8ibN8SnGSqWhQkTyD2c',
            rewardToken: 'Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1',
            rewardWrapper: 'EVVDA3ZiAjTizemLGXNUN3gb6cffQFEYkFjFZokPmUPz',
            nameStableCoin: 'FTTxFTT',
            referenceMainnet: 'xFTT-FTT',
          },
          ETHsoETH: {
            stableSwap: '4acW2PzwAxoZLSxj6w33Wvn2Af79bwCdJLdJGPY6HD3x',
            rewarderKey: 'rXhAofQCT7NN9TUqigyEAUzV1uLL4boeD8CRkNBSkYk',
            quarryKey: 'wrmcMSHFi3sWpAEy4rGDvQb3ezh3PhXoV2xNjgLBkKU',
            rewardToken: 'Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1',
            rewardWrapper: 'EVVDA3ZiAjTizemLGXNUN3gb6cffQFEYkFjFZokPmUPz',
            nameStableCoin: 'ETHsoETH',
            referenceMainnet: 'soETH-ETH',
          },
          USDCUXD: {
            stableSwap: 'KEN5P7p3asnb23Sw6yAmJRGvijfAzso3RqfyLAQhznt',
            rewarderKey: 'rXhAofQCT7NN9TUqigyEAUzV1uLL4boeD8CRkNBSkYk',
            quarryKey: 'BMMiE1bNCW61k3rw4Kfzx7er36JMrEsFGr1Bcng9i6Aq',
            rewardToken: 'Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1',
            rewardWrapper: 'EVVDA3ZiAjTizemLGXNUN3gb6cffQFEYkFjFZokPmUPz',
            nameStableCoin: 'USDCUXD',
            referenceMainnet: 'UXD-USDC',
          },
          WSOLstSOL: {
            stableSwap: 'Lid8SLUxQ9RmF7XMqUA8c24RitTwzja8VSKngJxRcUa',
            rewarderKey: 'rXhAofQCT7NN9TUqigyEAUzV1uLL4boeD8CRkNBSkYk',
            quarryKey: '2isVhcqVVpsAeZ94d1DGVErCQ7uZQNSJ85xikN8awHeC',
            rewardToken: 'Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1',
            rewardWrapper: 'EVVDA3ZiAjTizemLGXNUN3gb6cffQFEYkFjFZokPmUPz',
            nameStableCoin: 'WSOLstSOL',
            referenceMainnet: 'stSOL-SOL',
          },
          JSOLmSOL: {
            stableSwap: 'SoNcU2iwHMw6dGzsYNQkYFkUjwN1UdAjrWVRnStrZu2',
            rewarderKey: 'rXhAofQCT7NN9TUqigyEAUzV1uLL4boeD8CRkNBSkYk',
            quarryKey: '22qZzDhBckZxeZ2nojZbPqoZRoTq2NtUwDEv1jZEx2qK',
            rewardToken: 'Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1',
            rewardWrapper: 'EVVDA3ZiAjTizemLGXNUN3gb6cffQFEYkFjFZokPmUPz',
            nameStableCoin: 'JSOLmSOL',
            referenceMainnet: 'mSOL-JSOL',
          },
          
        },
        OrcaConfigAccount:''
      },
    ]
  }